// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_DiemTruongTieuHoc.Data;

#nullable disable

namespace QL_Diem.Migrations
{
    [DbContext(typeof(QLDiemDbContext))]
    [Migration("20260309055251_TaoCSDL")]
    partial class TaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QL_Diem.Data.HocSinh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LopHocID")
                        .HasColumnType("int");

                    b.Property<string>("MaHocSinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoaiPhuHuynh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LopHocID");

                    b.ToTable("HocSinh");
                });

            modelBuilder.Entity("QL_DiemTruongTieuHoc.Data.BangDiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DanhGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DiemCuoiKy")
                        .HasColumnType("float");

                    b.Property<double?>("DiemGiuaKy")
                        .HasColumnType("float");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HocSinhID")
                        .HasColumnType("int");

                    b.Property<int>("MonHocID")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HocSinhID");

                    b.HasIndex("MonHocID");

                    b.ToTable("BangDiem");
                });

            modelBuilder.Entity("QL_DiemTruongTieuHoc.Data.LopHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GiaoVienChuNhiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("QL_DiemTruongTieuHoc.Data.MonHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Mamon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("QL_Diem.Data.HocSinh", b =>
                {
                    b.HasOne("QL_DiemTruongTieuHoc.Data.LopHoc", "LopHoc")
                        .WithMany("HocSinh")
                        .HasForeignKey("LopHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QL_DiemTruongTieuHoc.Data.BangDiem", b =>
                {
                    b.HasOne("QL_Diem.Data.HocSinh", "HocSinh")
                        .WithMany("BangDiem")
                        .HasForeignKey("HocSinhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QL_DiemTruongTieuHoc.Data.MonHoc", "MonHoc")
                        .WithMany("BangDiems")
                        .HasForeignKey("MonHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QL_Diem.Data.HocSinh", b =>
                {
                    b.Navigation("BangDiem");
                });

            modelBuilder.Entity("QL_DiemTruongTieuHoc.Data.LopHoc", b =>
                {
                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("QL_DiemTruongTieuHoc.Data.MonHoc", b =>
                {
                    b.Navigation("BangDiems");
                });
#pragma warning restore 612, 618
        }
    }
}
